name: Coding standards

on:
    push:
        branches:
            - 'main'
    pull_request: ~

env:
    COMPOSER_ROOT_VERSION: dev-master

jobs:
    php-cs-fixer:
        name: PHP CS Fixer
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                  repository: marioblazek/coding-standard
                  path: vendor/marioblazek/coding-standard
            - uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --diff --dry-run
